// PLACEHOLDER — generated by `flutterfire configure` in a real setup.
//
// To run the live LLM chat surface, run `flutterfire configure` from
// `apps/openui_flutter_example/`. The CLI overwrites this file with
// project-specific config and registers the iOS/Android/Web apps.
//
// The stubs below let the example app compile without `flutterfire`
// being run. `Firebase.initializeApp(options:)` will fail at runtime
// with these values — that is intentional: the live demo requires a
// real Firebase project (see README "Live chat setup" section).
//
// The scripted demo (`Scripts` destination of `AppShell`) does not
// invoke Firebase and runs without this setup.

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Stub Firebase options. Replace by running `flutterfire configure`.
class DefaultFirebaseOptions {
  /// Returns platform-appropriate options. Stubs throw on use; configure
  /// Firebase first.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholder;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return _placeholder;
    }
  }

  static const FirebaseOptions _placeholder = FirebaseOptions(
    apiKey: 'REPLACE_VIA_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_VIA_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_VIA_FLUTTERFIRE_CONFIGURE',
    projectId: 'REPLACE_VIA_FLUTTERFIRE_CONFIGURE',
  );
}
