name: openui_test_helpers

on:
  pull_request:
    paths:
      - .github/workflows/openui_test_helpers.yml
      - packages/openui_test_helpers/**
  push:
    branches: [main]
    paths:
      - .github/workflows/openui_test_helpers.yml
      - packages/openui_test_helpers/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/openui_test_helpers
      min_coverage: 0
      dart_sdk: 3.11.5
